name: Build & Release WEmulate Frontend
on:
  release:
    types: [published]

jobs:
  build:
    name: Build & Release WEmulate Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install NPM Dependencies
        run: npm install
      - name: Build App
        run: npm run build
      - name: Create ZIP File
        run: cd build && zip -r ../release.zip .
      - name: Get Release Version
        id: release_version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Get latest release url
        id: latest_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.latest_release.outputs.upload_url }}
          asset_path: ./release.zip
          asset_name: release.zip
          asset_content_type: application/zip